# Generated by Django 5.1.6 on 2025-04-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Enter a title for your task...', max_length=100),
        ),
    ]
