# Generated by Django 5.1.6 on 2025-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_task_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('inprogress', 'In Progress'), ('review', 'Review'), ('complete', 'Complete')], default='backlog', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
