# Generated by Django 5.1.6 on 2025-05-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0017_remove_task_status_column_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
