# Generated by Django 5.1.6 on 2025-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_board_description_alter_board_name_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(help_text='Enter your project name...', max_length=255),
        ),
    ]
