# Generated by Django 5.1.6 on 2025-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chatmessage_deleted_chatmessage_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
