# Generated by Django 5.1.6 on 2025-04-08 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='users_online',
            field=models.ManyToManyField(blank=True, related_name='online_in_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
