# Generated by Django 5.1.6 on 2025-04-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_chatroom_users_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='deleted',
            new_name='delete_message',
        ),
    ]
